openapi: 3.0.0
info:
  title: Super Pagamentos API
  version: 1.0.0
  description: >
    API da plataforma Super Pagamentos. Esta seção documenta a rota de autenticação,
    responsável por gerar tokens JWT que permitem o acesso seguro às demais rotas protegidas.
paths:
  /auth:
    post:
      tags:
        - Autenticação
      summary: Autenticar
      description: >
        Esta rota autentica sua aplicação na plataforma **Super Pagamentos**.
        Ao fornecer sua `publicKey` e `secretKey`, você receberá tokens JWT (`access_token` e `refresh_token`)
        que devem ser usados para acessar as rotas protegidas da API.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - publicKey
                - secretKey
              properties:
                publicKey:
                  type: string
                  example: "suaPublicKeyAqui"
                secretKey:
                  type: string
                  example: "suaSecretKeyAqui"
      responses:
        "200":
          description: Autenticado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5c..."
                      refresh_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI..."
                      expires_in:
                        type: string
                        example: "3600s"
                  message:
                    type: string
                    example: Autenticado com sucesso!
        "400":
          description: Requisição inválida (credenciais incorretas).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Credenciais inválidas.
      security: []
      x-codeSamples:
        - lang: cURL
          label: Exemplo em cURL
          source: |
            curl -X POST https://api.superpagamentos.com/auth \
              -H "Content-Type: application/json" \
              -d '{
                "publicKey": "suaPublicKeyAqui",
                "secretKey": "suaSecretKeyAqui"
              }'
        - lang: PHP
          label: Exemplo em PHP
          source: |
            <?php
            $data = [
              "publicKey" => "suaPublicKeyAqui",
              "secretKey" => "suaSecretKeyAqui"
            ];
            $options = [
              'http' => [
                'method'  => 'POST',
                'header'  => "Content-type: application/json",
                'content' => json_encode($data)
              ]
            ];
            $context  = stream_context_create($options);
            $result = file_get_contents('https://api.superpagamentos.com/auth', false, $context);
            echo $result;
        - lang: Node.js
          label: Exemplo em Node.js (Axios)
          source: |
            const axios = require('axios');
            axios.post('https://api.superpagamentos.com/auth', {
              publicKey: 'suaPublicKeyAqui',
              secretKey: 'suaSecretKeyAqui'
            })
            .then(response => console.log(response.data))
            .catch(error => console.error(error.response.data));
